### ISSUE TITLE
Maybe archive this repo and link to an updated fork?

### ISSUE THREAD

**Issue by mastercoms** [SRombauts/UE4GitPlugin#169]
I've been maintaining an updated version of this plugin here: https://github.com/ProjectBorealis/UEGitPlugin

It has UE5+4.27 support, many bug and performance fixes and enhanced functionality which make it much more ready for production, and it has been battle tested in real world use.

I have seen that you have limited time to maintain this repo, and maybe it would be best for new users to be redirected to this updated version.

**Comment by mastercoms** [comment]
Yes it does work on 4.27. I've fixed a lot of issues with sync/pull, including crashes, so let me know if there's still work to do in that area :)

**Comment by dacanizares** [comment]
Thanks!

**Comment by SRombauts** [comment]
Hello @mastercoms, you are right indeed, I should consider this seriously!
I always intended to come back to this plugin and make it a bit more up to date, since I am now using it again, though without LFS.
I made some local changes for my own use recently, I'll see if I can resume doing some updates, and have to decide.

In the meantime, I did push an update to the readme with a link to your fork!
And please don't hesitate to suggest more changes to the text on the readme

Cheers!
Sébastien

**Comment by ameaninglessname** [comment]
Glad to see you are back, and long live the git plugin🤘

**Comment by mastercoms** [comment]
Thanks so much! If you do end up resuming development on this, I would be happy to merge in changes from the fork.

**Comment by SRombauts** [comment]
Hey @mastercoms,
I am slowly resuming some development on this in my little spare time like now.
I have also merged some PR without testing everything, and I am pretty sure there are some things I'll need to fix in the coming weeks
If you are willing to contribute back some of your changes I would be happy to integrate them :)
I actually already looked at some of your changes more than once, but I was only looking for specific issues, and I didn't check at the main "LFS perf improvement"

Ultimately the goal would be to contribute back this to UE5 :)

**Comment by mastercoms** [comment]
Awesome! I'll try to in the near future

**Comment by SRombauts** [comment]
You also did implement support for branches IIRC, this would be really
useful and is one I had started an implementation just a few weeks ago
