### ISSUE TITLE
LFS 2: unable to unlock unmodified files in UE 4.20

### ISSUE THREAD

**Issue by JuKu** [SRombauts/UE4GitPlugin#79]
Hi,

we are using Unreal Engine 4.20 with your git plugin.
Also we have a git repository with LFS enabled and want to lock files.
So we opened a .umap file and click on "Source Control" --> "Checkout". This works fine and it seems to be the file was locked.
Now first **question**: is this file locked only locally or also on remote (origin) repository?
And next: How can i unlock the file if i dont want to make any changes to this file?

Thank you!

**Comment by JuKu** [comment]
On locking i get this message:
```
The following assets could not be successfully checked out from source control:
/Game/Maps/Hallway
```

But after this message the lock is set:
![dd](https://user-images.githubusercontent.com/1138046/44105701-c559155e-9ff2-11e8-8289-40c3d00c7a00.PNG)

But i cannot unlock the file:
![ddkopie](https://user-images.githubusercontent.com/1138046/44105730-e3356942-9ff2-11e8-8bc1-ea6f11797c8e.PNG)

**Comment by SRombauts** [comment]
Are you using a github repository? You need Git LFS 2 support on the server! 
I'll also have a look at the log file, and let you know. 

To answer your questions:
1. Locks are supposed to be server side, but the server needs to support this!
2. Unlock is normally done with revert (not working for you...) 

But for sure, using a server without proper git lfs 2 file locks support  should not leads to your broken situation. My bad!

**Comment by JuKu** [comment]
@SRombauts I am using a self-hosted gitlab installation with enabled git lfs support.
I can also manually lock and unlock files with git console.

![dd](https://user-images.githubusercontent.com/1138046/44313911-0039fe00-a411-11e8-9517-064243c71096.PNG)

![ddkopie](https://user-images.githubusercontent.com/1138046/44313931-6161d180-a411-11e8-90df-99b5b7c92851.PNG)

So i think git lfs is enabled and works fine on server, or?

**Comment by SRombauts** [comment]
Indeed Gitlab seems to support file locking, at long last!

So I'll check this, I think it might be a bug in the way the plugin handle locking. I was developed and tested with Github only, and might not parse the results in a generic way.

**Comment by JuKu** [comment]
@SRombauts Thanks!

**Comment by sensvos** [comment]
Hello, it seems like recognizing _Locked_ files as revertable did the job for me:

GitSourceControlState.cpp:
```
bool FGitSourceControlState::CanRevert() const
{	
	return IsModified() || LockState == ELockState::Locked; // Allow reverting locked, unchanged files.
}

```

It works as expected, yet I am not sure if it does not have other implications, I am looking forward to hearing from you about your insight.

**Comment by SRombauts** [comment]
Ooh, yes! This is a new thing from 4.20!
A colleague of mine changed UE4.20 to actually use CanRevert()!

**Comment by JuKu** [comment]
@SRombauts I understand.
Thanks for that information! :)

**Comment by sensvos** [comment]
Argh, sorry it seems like I modified the GetMissingVsExistingFiles() function as well and I forgot about it, I totally agree :)

**Comment by JuKu** [comment]
@SRombauts Thanks for that great support!

@SRombauts How can i use the new version of plugin?
Do i have to compile it self or does UE4 already compiling the plugin itself?

**Comment by SRombauts** [comment]
@JuKu I'll release a new version of the plugin quite soon, still need some testing

**Comment by JuKu** [comment]
@SRombauts Is there a new version out there?

**Comment by alexgchap** [comment]
Hello, 
First of all, great plugin!

Sadly, I am experiencing the same issue as mentioned above. 

I am using gitea, a self-hosted git server taht supports git lfs 2.0.
When using **source control > checkout** on a .uasset in UE's content browser,
The file actually gets locked on the server, which is great. 

The problem is that I also get the error : 
"The following assets could not be successfully checked out from source control: 
xxx.uasset"

I am then unable to **submit to source control** or even **revert**...
When I **submit to source control**, the plugin prompts (in the lower right corner) No assets to check in...

I am using UE4.22
Is there any update on this? This is a roadblock for me...

**Comment by SRombauts** [comment]
Hi @alexgchap and @JuKu, I have released many versions of the plugin since this issue has been closed: if it is still not working for you, I would like you to open a new bug report, with some log to help me diagnose and think of a fix.
Also, as stated elsewhere, I am not using LFS anymore so the support is not that good on my part as I would love too, sorry.

Sébastien
